name: Main

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  prek:
    name: Prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run prek
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2.0.3

  test:
    name: Test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Test gist
        uses: ./
        with:
          file: test/coverage.txt
          type: go
          gist-id: ${{ vars.GIST_ID }}
          gist-token: ${{ secrets.GIST_TOKEN }}

      - name: Test orphan branch
        uses: ./
        with:
          file: test/lcov.info
          type: lcov

  github-deploy:
    name: Release to GitHub
    if: github.ref_type == 'tag'
    needs: [prek, test]
    environment: github-releases
    permissions:
      contents: write
    env:
      CHANGELOG: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
      PRERELEASE: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create GitHub Release
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --notes="See [the CHANGELOG](${CHANGELOG}) for more details." \
            --draft="${PRERELEASE}" \
            --prerelease="${PRERELEASE}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move major and minor tags
        if: env.PRERELEASE != 'true'
        run: |
          MAJOR="${GITHUB_REF_NAME%%.*}"
          MINOR="${GITHUB_REF_NAME%.*}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git tag -fa "${MAJOR}" -m "chore(release): ${GITHUB_REF_NAME}"
          git tag -fa "${MINOR}" -m "chore(release): ${GITHUB_REF_NAME}"
          git push origin -f "refs/tags/${MAJOR}" "refs/tags/${MINOR}"
